import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import DropZoneComponent from "@/components/DropZoneComponent";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [file, setFile] = useState<any>(null);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col items-center justify-center">
          <h1 className="my-4 text-3xl font-medium">Got a File?</h1>
          <div className="flex flex-col items-center justify-center bg-gray-800 shadow-xl w-96 rounded-xl">
            {/* Drop Zone */}
            <DropZoneComponent setFile={setFile} />
            {/* Render File */}
            {file ? file.name : ""}
            {/* Upload Button */}
          </div>
        </div>
      </main>
    </>
  );
}
