import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import DropZoneComponent from "@/components/DropZoneComponent";
import { useState } from "react";
import RenderFile from "@/components/RenderFile";
import axios from "axios";
import DownloadFile from "@/components/DownloadFile";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [file, setFile] = useState<any>(null);
  const [id, setId] = useState(null);
  const [downloadPageLink, setDownloadPageLink] = useState(null);
  const [uploadState, setUploadState] = useState<
    "Uploading" | "Upload Failed" | "Uploaded" | "Upload"
  >("Upload");

  const handleUpload = async () => {
    if (uploadState == "Uploading") return;
    setUploadState("Uploading");
    const formData = new FormData();
    formData.append("myFile", file);
    try {
      const { data } = await axios({
        method: "post",
        data: formData,
        url: "api/files/upload",
        headers: {
          "Content-Type": "multipart/form-data",
        },
      });
      setDownloadPageLink(data.downloadPageLink);
      setId(data.id);
    } catch (error: any) {
      console.log(error.response.data);
      setUploadState("Upload Failed");
    }
  };

  const resetComponent = () => {
    setFile(null);
    setDownloadPageLink(null);
    setUploadState("Upload");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col items-center justify-center">
          <h1 className="my-4 text-3xl font-medium">Got a File?</h1>
          <div className="flex flex-col items-center justify-center bg-gray-800 shadow-xl w-96 rounded-xl">
            {/* Drop Zone */}
            {!downloadPageLink && <DropZoneComponent setFile={setFile} />}

            {/* Render File */}
            {file && (
              <RenderFile
                file={{
                  format: file.type.split("/")[1],
                  name: file.name,
                  sizeInBytes: file.size,
                }}
              />
            )}
            {/* Upload Button */}
            {!downloadPageLink && file && (
              <button
                className="p-2 my-5 bg-gray-900 rounded-md w-44 focus:outline-none"
                onClick={handleUpload}
              >
                Upload
              </button>
            )}
            {downloadPageLink && (
              <div className="p-2 text-center">
                <DownloadFile downloadPageLink={downloadPageLink} />
                {/* Email Form */}
                <button
                  className="p-2 my-5 bg-gray-900 rounded-md w-44 focus:outline-none"
                  onClick={resetComponent}
                >
                  Upload New File
                </button>
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
